spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.56.24.127:3306/nideshop
    username: root
    password: ZW@zgy_1207
    #接口返回对象中的日期格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 8088

mybatis:
  #mapper.xml存放路径（resource）
  mapper-locations: classpath:mapper/*.xml
  #mapper接口文件存放路径
  type-aliases-package: com.xinba.supermarket.dao
#引入日志文件
logging:
  config: classpath:config/log-spring.xml